\input texinfo
@documentencoding ISO-8859-1
@setfilename gpgex.info
@include version.texi
@settitle The GpgEX Technical Manual

@dircategory GnuPG Plugin
@direntry
* gpgex: (gpgex).              An extension for the Windows shell.
@end direntry


@c Unify some of the indices.
@syncodeindex tp fn
@syncodeindex pg fn

@copying
This is @cite{The GpgEX Technical Manual} for @acronym{GpgEX} (version
@value{VERSION}, @value{UPDATED-MONTH}).

@iftex
Published by g10 Code GmbH@*
Hüttenstr. 61@*
40699 Erkrath, Germany
@end iftex

Copyright @copyright{} 2007 g10 Code GmbH

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version. The text of the license can be found in the
section entitled ``Copying''.
@end quotation
@end copying

@c
@c Titlepage
@c
@setchapternewpage odd
@titlepage 
@title The GpgEX Technical Manual
@subtitle Version @value{VERSION}
@subtitle @value{UPDATED-MONTH}

@sp 3

@sp 3

@author Werner Koch (@email{wk@@gnupg.org})

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@ifnothtml
@contents
@page
@end ifnothtml

@c @ifhtml
@c @center @image{logo}
@c @end ifhtml

@ifnottex
@node Top
@top 

@insertcopying

@noindent
This file documents @acronym{GpgEX}; a GnuPG plugin for the Windows shell.
@end ifnottex


@menu
* Introduction::                How to use this manual.
* Assuan Protocol::             Description of the UI server protocol.

Appendices

* Copying::                     The GNU General Public License says how you
                                can copy and share this manual.

Indices

* Concept Index::               Index of concepts and programs.
* Function and Data Index::     Index of functions, variables and data types.

@end menu

@ifhtml
@page
@summarycontents
@contents
@end ifhtml

@c
@c  I N T R O
@c
@node Introduction
@chapter Introduction
Bla bla


@c
@c  P R O T O C O L  D E S C R I P T I O N
@c
@node Assuan Protocol
@chapter Description of the UI Server Protocol

All cryptographic operations are done by this server and the server is
responsible for all dialogs.  If a a server is not available,
@acronym{GpgEX} does not work.

This protocol used between @acronym{GpgEX} and the User Interface Server
(UI server) is specified in the `GPGME Reference Manual', under the
heading `The GnuPG UI Server Protocol'.


@include gpl.texi

@c
@c  I N D E X E S
@c
@node Concept Index
@unnumbered Concept Index
@printindex cp
@node Function and Data Index
@unnumbered Function and Data Index
@printindex fn

@bye


@c Local Variables:
@c coding: latin-1
@c End:
